FROM node:lts-alpine AS build_image

WORKDIR /app/
# COPY **/package.json **/package-lock.json ./
COPY package.json ./

RUN npm install
#COPY ./reactjs_aspnetapi_dockerized /app/
COPY . /app/

RUN npm run build

# Production stage
FROM node:lts-alpine AS prod_image
WORKDIR /app

COPY --from=build_image /app/dist/ /app/dist/

RUN npm install serve -g

COPY **/package.json **/package-lock.json ./

EXPOSE 80

# CMD ["npm", "run", "dev"]

CMD ["serve", "-p", "80" ,"-s", "dist"]